/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package improviso.gui;
import improviso.*;
import java.io.*;
import java.awt.Dimension;
import javax.sound.midi.InvalidMidiDataException;
import javax.sound.midi.MidiUnavailableException;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;

/**
 *
 * @author User
 */
public class Main extends javax.swing.JFrame {
    final private SectionPanel sectionPanel;
    final private CompositionController controller = new CompositionController();
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        sectionPanel = new SectionPanel(this.controller);
        tabs.add("Section", sectionPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLoadFile = new javax.swing.JButton();
        btnPlayFile = new javax.swing.JButton();
        tabs = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));

        btnLoadFile.setText("File");
        btnLoadFile.setName("btnLoadFile"); // NOI18N
        btnLoadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadFileActionPerformed(evt);
            }
        });

        btnPlayFile.setText("Play");
        btnPlayFile.setEnabled(false);
        btnPlayFile.setName("btnPlayFile"); // NOI18N
        btnPlayFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayButtonActionPerformed(evt);
            }
        });

        tabs.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabs)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLoadFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPlayFile)
                        .addGap(0, 760, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoadFile)
                    .addComponent(btnPlayFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public SectionConfiguration getSectionConfiguration(String sectionId) {
        return controller.getSectionConfiguration(sectionId);
    }
    
    public void applyChangesToSection(String sectionId, SectionConfiguration config) {
        controller.applyChangesToSection(sectionId, config);
    }
    
    public void playSection(String sectionId) {
        try {
            this.controller.playSection(sectionId);
        } catch (InvalidMidiDataException | ImprovisoException | IOException | MidiUnavailableException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error playing section: " + ex.getMessage());
        }
    }
    
    private void btnLoadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadFileActionPerformed
        final JFileChooser fc = new JFileChooser();
        fc.setPreferredSize(new Dimension(1200, 800));
        fc.setCurrentDirectory(new File("."));
        if(fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                controller.openComposition(fc.getSelectedFile().getAbsolutePath());
                this.btnPlayFile.setEnabled(true);
                this.sectionPanel.setSectionList(controller.getSectionList());
            } catch (ImprovisoException ex) {
                JOptionPane.showMessageDialog(rootPane, "Error creating composition: " + ex.getMessage());
            } catch (ParserConfigurationException ex) {
                JOptionPane.showMessageDialog(rootPane, "Configuration error: " + ex.getMessage());
            } catch (SAXException ex) {
                JOptionPane.showMessageDialog(rootPane, "Error parsing XML file: " + ex.getMessage());
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(rootPane, "Error reading file: " + ex.getMessage());
            }
        };
        
    }//GEN-LAST:event_btnLoadFileActionPerformed

    private void btnPlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayButtonActionPerformed
        if (controller.isCompositionLoaded()) {
            try {
                controller.playComposition();
            } catch (InvalidMidiDataException | ImprovisoException | IOException | MidiUnavailableException ex) {
                JOptionPane.showMessageDialog(rootPane, "Error playing composition: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnPlayButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoadFile;
    private javax.swing.JButton btnPlayFile;
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables

}
